master:
  build: .
  hostname: master
  expose:
   - 6322/udp
   - 6322/tcp
   - 6323
   - 6324
   - 6325
  command: /bin/bash
  stdin_open: true
  tty: true
node1:
  build: .
  hostname: node1
  links:
   - master:master
  command: /bin/bash
  stdin_open: true
  tty: true
node2:
  build: .
  hostname: node2
  links:
   - master:master
  command: /bin/bash
  stdin_open: true
  tty: true
node3:
  build: .
  hostname: node3
  links:
   - master:master
  command: /bin/bash
  stdin_open: true
  tty: true
  
